repo: openworm/sibernetic
shortDescription: "This is a C++/OpenCL implementation of the PCISPH algorithm supplemented with a set of biomechanics simulations related features applied to C. elegans locomotion"
coordinator: palyanov.andrey@openworm.org
documentation: "https://openworm.github.io/sibernetic/"
gitter: "http://gitter.im/openworm/sibernetic"
inputs: 
  - openworm/CElegansNeuroML
keywords: 
  - simulation
  - physics
  - particles
  - worm body
languages: 
  - python
latest-release:
  - 0.0.3
members: 
  - stephen@openworm.org
  - skhayrulin@openworm.org
outputs: 
  - openworm/CElegansNeuroML
parent: 
  - openworm/OpenWorm
children: 
  - openworm/sibernetic_NEURON
